// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUP911RMnCdxiQOztM24bRlJ3WBOeTro',
    appId: '1:721135046075:web:29e9dd40e63c6268c0489e',
    messagingSenderId: '721135046075',
    projectId: 'logistic-project-f3028',
    authDomain: 'logistic-project-f3028.firebaseapp.com',
    storageBucket: 'logistic-project-f3028.appspot.com',
    measurementId: 'G-JCJ221EJ90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbO6V1e5mqoQHObN2dpycyCpsSsoTf2s',
    appId: '1:721135046075:android:4fcdf3ff758ca7fec0489e',
    messagingSenderId: '721135046075',
    projectId: 'logistic-project-f3028',
    storageBucket: 'logistic-project-f3028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQRr8kUwYlKzbQgCsB321-TQd-uGmwfc',
    appId: '1:721135046075:ios:59b0989dae0ab847c0489e',
    messagingSenderId: '721135046075',
    projectId: 'logistic-project-f3028',
    storageBucket: 'logistic-project-f3028.appspot.com',
    iosBundleId: 'com.example.welecomeLoginOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQRr8kUwYlKzbQgCsB321-TQd-uGmwfc',
    appId: '1:721135046075:ios:1688a74f3a9c098bc0489e',
    messagingSenderId: '721135046075',
    projectId: 'logistic-project-f3028',
    storageBucket: 'logistic-project-f3028.appspot.com',
    iosBundleId: 'com.example.welecomeLoginOut.RunnerTests',
  );
}
