name: welecome_login_out
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  dropdown_button2: ^3.0.0-beta.12  
  geocoding: ^3.0.0
  skeleton_text: ^3.0.1  
  velocity_x:
  http:
  shared_preferences:
  jwt_decoder:
  flutter_slidable: 
  google_maps_flutter: ^2.5.3
  flutter_svg: ^0.22.0
  flutter_localizations:
        sdk: flutter
  intl: any      

  cupertino_icons: ^1.0.2
  flare_flutter: ^3.0.2
  flutter_riverpod: ^2.5.1
  transparent_image: ^2.0.1
  get: ^4.6.6
  uuid: ^4.3.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  cloud_firestore: ^4.15.9
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^9.0.0
  flutter_charts: ^0.5.2
  fl_chart: ^0.67.0
  syncfusion_flutter_charts: ^25.1.41+1
  responsive_sizer: ^3.3.1
  
  syncfusion_flutter_datepicker: ^25.2.5
  rxdart: ^0.27.7
  flutter_rating_bar: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  
  assets:
    - assets/
    - assets/images/mainTop.png
    - assets/images/MainPage.png
    - assets/images/signup.png
    - assets/images/Forgot-password.png
    - assets/images/Login.png
    - assets/images/Secure-login.png
    - assets/images/reset.png
    - assets/images/logo.png    
    - assets/images/profile.png
    - assets/images/menu.png
    - assets/images/add_product.png
    - assets/images/add_warehouse.png
    - assets/images/add_product0.png
    - assets/images/unknown_product.jpg
    - assets/images/store_icon.png
    - assets/images/store_icon0.png
    - assets/images/store_icon1.png
    - assets/images/manageEmployee.png
    - assets/images/add_employee.png
    - assets/images/info_employee.png
    - assets/images/edit_employee.png 
    - assets/images/dashboard.png
    - assets/images/Checklist.png
    - assets/images/sudia.png
    - assets/images/us.png
    
flutter_intl:
  enabled: true

